server:
  port: 8081

logging:
  config: classpath:logback.xml


#dubbo:
#  application:
#    name:  dubbo-provider
#  registry:
#    address: zookeeper://192.168.88.128:2181
#    timeout: 60000
#  protocol:
#    name: dubbo
#    port: 20881
#  scan:
#    base-packages: org.producer.impl


