server:
  port: 8070
spring:
  autoconfigure:
    exclude: com.wow.gatewaydiverse.nacos.ApiNacosAutoConfiguration
  #    exclude: com.wow.gatewaydiverse.zookeeper.ApiZookeeperAutoConfiguration
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  application:
    name: wow
api:
  serviceId: backend-http-server
  # 异构微服务的IP
  ip: 127.0.0.1
  # 异构微服务的端口
  port: 8060
  # 异构微服务的健康检查URL
  health-check-url: http://localhost:8060/health.json
  env: dev
  version: 1.0.0
