server:
  port: 8085
api:
  registerAddress: 192.168.88.128:2181
  env: dev
#api.gray=true
#api.registerAddress=127.0.0.1:8848

#spring.data.mongodb.rui = mongodb://127.0.0.1:27017/test
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always